### ISSUE TITLE
Bypass Docker Hub pull rate limits

### ISSUE THREAD

**Issue by nwu63** [mdolab/.github#3]
# Description of feature
Currently, many builds on Travis fail due to Docker Hub rate limiting:
```
toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

# Potential solution
Maybe we will want to authenticate all `docker pull` commands (when possible, i.e. builds triggered by the mdolab organization), even for the `public` images.

**Comment by nwu63** [comment]
@sseraj this is done right?

**Comment by sseraj** [comment]
Yes, this is done. Closing.
