### ISSUE TITLE
Investigate using config as code

### ISSUE THREAD

**Issue by ewu63** [mdolab/.github#7]
# Description
We have too many repos, and managing their configs become difficult/time consuming. We should look into using [probot/settings](https://github.com/probot/settings) to store some centralized repository settings which can be shared across all the repos and keep everything in sync, especially for things like
- required status checks
- number of required review approvals
- enforce linear history

However, security/access becomes an issue so we have to be really careful about this. If someone gets write access to this file they can basically change the repo however they want. We may want to add extra protections or something.

**Comment by nwu63** [comment]
[this](https://github.com/github/safe-settings) is a potential alternative without relying on probot. Basically the same idea though.
